# This is the base sweep configuration that sets the entity and the project accordingly
project: final-report
entity: platypus-dgm
count: 10000

# Change the name of the run to [in_distribution_dataset]_vs_[out_of_distribution_dataset]_[run_name]
# using the dysweep name changer for better readability
run_name_changer:
  expression: |
    from meta_configurations import *
  function_of_interest: ood_run_name_changer
