project: local-optimization-dysweep
entity: platypus-dgm
default_root_dir: experiments/ood/sweeps
count: 10000

# BASE configuration which is being used
base_config:
  ood:
    pick_single: True
    method: ood.methods.local_optimization.OODLocalOptimization
    method_args:
      intermediate_image_log_frequency: 20
      optimization_objective: nll

sweep_configuration:
  method: grid
  metric:
    goal: minimize
    name: nll
  parameters:
    ood:
      method_args:
        dy__upsert:
          - sweep: True
            sweep_identifier: Z_optimizer
            sweep_alias:
              - LBFGS
              - SGD
              - Adam
            values:
              - optimization_steps: 50
                optimizer: torch.optim.LBFGS
                optimizer_args:
                  line_search_fn: strong_wolfe
              - optimization_steps: 500
                optimizer: torch.optim.SGD
                optimizer_args:
                  lr: 0.001
              - optimization_steps: 500
                optimizer: torch.optim.Adam
                optimizer_args:
                  lr: 0.01
          - sweep: True
            sweep_identifier: Z_representation_rank
            sweep_alias:
            - input
            - shallow
            - middle
            - deep
            values:
            - representation_rank: null
            - representation_rank: 10
            - representation_rank: 25
            - representation_rank: 43

    dy__upsert:
      - sweep: True
        sweep_identifier: B_dataset
        sweep_alias:
          - flow_fmnist
          - flow_cifar10
          - flow_svhn
          - flow_mnist
        values:
          - base_model:
              run_dir: runs/flow_fmnist
              config_dir: experiments/training/flow_elaborate_fmnist.yaml
              checkpoint_dir: runs/flow_fmnist/checkpoints/de_nf_latest.pt
          - base_model:
              run_dir: runs/flow_cifar10
              config_dir: experiments/training/flow_elaborate_cifar10.yaml
              checkpoint_dir: runs/flow_cifar10/checkpoints/de_nf_latest.pt
          - base_model:
              run_dir: runs/flow_svhn
              config_dir: experiments/training/flow_elaborate_svhn.yaml
              checkpoint_dir: runs/flow_svhn/checkpoints/de_nf_latest.pt
          - base_model:
              run_dir: runs/flow_mnist
              config_dir: experiments/training/flow_elaborate_mnist.yaml
              checkpoint_dir: runs/flow_mnist/checkpoints/de_nf_latest.pt
          
      - sweep: True
        sweep_identifier: C_ood_or_not
        sweep_alias:
          - ood_for_test
          - in_distr_for_test
        values:
          - data:
              in_distribution:
                dataloader_args:
                  dataset:
                    dy__eval:
                      expression: |
                        from pprint import pprint

                        def func(conf):

                          last_part = conf['base_model']['run_dir'].split('_')[-1]
                          if last_part == 'fmnist':
                            return 'fashion-mnist'
                          if last_part == 'cifar10':
                            return 'cifar10'
                          if last_part == 'mnist':
                            return 'mnist'
                          if last_part == 'svhn':
                            return 'svhn'
                      function_of_interest: func
              out_of_distribution:
                dataloader_args:
                  dataset:
                    dy__eval:
                      expression: |
                        from pprint import pprint

                        def func(conf):

                          last_part = conf['base_model']['run_dir'].split('_')[-1]
                          if last_part == 'fmnist':
                            return 'mnist'
                          if last_part == 'cifar10':
                            return 'svhn'
                          if last_part == 'mnist':
                            return 'fashion-mnist'
                          if last_part == 'svhn':
                            return 'cifar10'
                      function_of_interest: func
          - data:
              in_distribution:
                dataloader_args:
                  dataset:
                    dy__eval:
                      expression: |
                        from pprint import pprint
                        def func(conf):

                          last_part = conf['base_model']['run_dir'].split('_')[-1]
                          if last_part == 'fmnist':
                            return 'fashion-mnist'
                          if last_part == 'cifar10':
                            return 'cifar10'
                          if last_part == 'mnist':
                            return 'mnist'
                          if last_part == 'svhn':
                            return 'svhn'
                      function_of_interest: func
              out_of_distribution:
                dataloader_args:
                  dataset:
                    dy__eval:
                      expression: |
                        from pprint import pprint

                        def func(conf):
                          last_part = conf['base_model']['run_dir'].split('_')[-1]
                          if last_part == 'fmnist':
                            return 'fashion-mnist'
                          if last_part == 'cifar10':
                            return 'cifar10'
                          if last_part == 'mnist':
                            return 'mnist'
                          if last_part == 'svhn':
                            return 'svhn'
                      function_of_interest: func
      - sweep: True
        sweep_identifier: A_seed
        sweep_alias:
          - seed1
          - seed2
          - seed3
        values:
          - data:
              seed: 10
            ood:
              seed: 11
          - data:
              seed: 20
            ood:
              seed: 21
          - data:
              seed: 30
            ood:
              seed: 31
